# Generated by Django 5.0.4 on 2024-05-07 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLoadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_loaded", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="boxtobox",
            name="points_received",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="username"
            ),
        ),
    ]
